### ISSUE TITLE
Same for debian 

### ISSUE THREAD

**Issue by mabed-fr** [hifis-net/ubuntu-systemd#10]
Hello,

The same thing for the maintained versions of debian and the one in testing? (n-1 , n n n+1) 

is it possible ?

**Comment by tobiashuste** [comment]
Dear @mabed-fr, I think I don't really get your point. Could you please explain again what you have in mind?

**Comment by mabed-fr** [comment]
Hello,

I want the same image for debian but i find it

**Comment by tobiashuste** [comment]
Closing in favor of https://github.com/hifis-net/debian-systemd/issues/11
